### ISSUE TITLE
不能在DialogFragment里面使用

### ISSUE THREAD

**Issue by faith-hb** [H07000223/FlycoTabLayout#329]
不能在DialogFragment里面使用，报错信息：
java.lang.IllegalArgumentException: No view found for id 0x7f0a00a2 (com.zhiji.hawkeye:id/dataTimeContainer) for fragment CustomTimeFragment{cd3aae9 #8 id=0x7f0a00a2}
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by ymwm-lxl** [comment]
是的，我也遇到了同样的问题，希望作者能够及时修改

**Comment by SergeyAppDroid** [comment]
@faith-hb did you solve this problem?
