### ISSUE TITLE
BUG android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by ybADMIN** [H07000223/FlycoTabLayout#37]
`Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                            at android.content.res.Resources.getValue(Resources.java:1302)
                                                                            at android.content.res.MiuiResources.getValue(MiuiResources.java:124)
                                                                            at android.content.res.Resources.getDrawable(Resources.java:821)
                                                                            at android.content.res.Resources.getDrawable(Resources.java:788)
                                                                            at com.flyco.tablayout.CommonTabLayout.setMsgMargin(CommonTabLayout.java:863)
                                                                            at com.flyco.tablayout.CommonTabLayout.showMsg(CommonTabLayout.java:809)
                                                                            at com.huanmedia.yourchum.mvp.ui.notifcation.notificationreply.NotificationReplyActivity.initView(NotificationReplyActivity.java:130)
                                                                            at com.huanmedia.yourchum.mvp.ui.notifcation.notificationreply.NotificationReplyActivity.onCreate(NotificationReplyActivity.java:81)
                                                                            at android.app.Activity.performCreate(Activity.java:6051)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5269) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705) `
固定宽度
 notificationReplySt.setTabWidth(DisplayUtil.px2dip(this, DisplayUtil.getDisplayWidth(this) / 2));
CommonTabLayout 在设置消息的时候报错
 notificationReplySt.showMsg((selecsion==0?1:0),count);

**Comment by ybADMIN** [comment]
失误，由于没有隐藏icon造成的
