### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference

### ISSUE THREAD

**Issue by shadowline** [H07000223/FlycoTabLayout#38]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
	at com.flyco.tablayout.CommonTabLayout.c(CommonTabLayout.java)
	at com.flyco.tablayout.CommonTabLayout.setCurrentTab(CommonTabLayout.java)
	at com.richinfo.drive.activity.MainActivity.assignViews(MainActivity.java)
	at com.richinfo.drive.activity.MainActivity.onCreate(MainActivity.java)
	at android.app.Activity.performCreate(Activity.java:6060)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2715)
	at android.app.ActivityThread.access$800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:199)
	at android.app.ActivityThread.main(ActivityThread.java:5783)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)

**Comment by lyhgzx** [comment]
我也遇到这个问题，希望楼主找找原因，拜托了

**Comment by rw15250** [comment]
Process: com.android.dialer, PID: 30690
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
                                                       at com.qucii.tablayout.SegmentTabLayout.calcIndicatorRect(SegmentTabLayout.java:287)
                                                       at com.qucii.tablayout.SegmentTabLayout.onDraw(SegmentTabLayout.java:392)
                                                       at android.view.View.draw(View.java:16195)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15192)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.View.draw(View.java:15965)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3742)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3532)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15187)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3726)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3706)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15152)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
只有两个tab，第一次进去快速滑动，从1到2，到2后竟然还可以继续滑动，显示的是1界面，然后就崩了。

**Comment by rw15250** [comment]
空指针一般都是生命周期的问题，fragment里可以放在onviewcreate初始化

**Comment by JakeWang123** [comment]
我也遇到这个问题，我的是fragment 里面通过SegmentTabLayout嵌套3个fragment，在第三个fragment里面点击一个按钮跳到另外一个activity 返回到 SegmentTabLayout 的第三个fragment 滑动报这个错误

**Comment by curiousleast** [comment]
第一遍就没报，，敲第二遍就报

**Comment by MakeCodeFly** [comment]
我也遇到这个问题  请问各位怎么解决的

**Comment by VitaliBov** [comment]
You need to do a check:

```
private List<Fragment> tabs = new ArrayList<>();
private PagerAdapter pagerAdapter;

public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment, container, false);
        initTabs();
        return view;
}

private void initTabs() {
        if (pagerAdapter == null) {
            pagerAdapter = new PagerAdapter(getChildFragmentManager());
        }
        if (tabs.isEmpty()) {
            tabs.add(FirstFragment.newInstance());
            tabs.add(SecondFragment.newInstance());
        }
        viewPager.setAdapter(pagerAdapter);
        tabLayout.setTabData(titles);
        tabLayout.setOnTabSelectListener(position -> viewPager.setCurrentItem(position));
        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }

            @Override
            public void onPageSelected(int position) {
                tabLayout.setCurrentTab(position);
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });
}
```

**Comment by protectedMan** [comment]
最后怎么解决的。。。

**Comment by Lee987** [comment]
mIndicatorAnimEnable为true时会执行calcOffset()方法，可以尝试设置mIndicatorAnimEnable为false绕过该方法。可以解决问题。但是希望有更好的方法解决
