### ISSUE TITLE
SlidingTabLayout滑动时报错  

### ISSUE THREAD

**Issue by cdcdec** [H07000223/FlycoTabLayout#391]
``java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.flyco.tablayout.SlidingTabLayout.updateTabSelection(SlidingTabLayout.java:368)
        at com.flyco.tablayout.SlidingTabLayout.onPageSelected(SlidingTabLayout.java:330)
        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1941)
        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:680)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:664)
        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2257)
        at android.view.View.dispatchTouchEvent(View.java:10946)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2836)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2512)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:624)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1909)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:586)
        at android.view.View.dispatchPointerEvent(View.java:11175)

**Comment by cdcdec** [comment]
找到原因了，把tab标题的集合传进去就行了。tablayout.setViewPager(all_group_vp,groupTitles)
