### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference         at com.flyco.tablayout.SlidingTabLayout.showMsg(SlidingTabLayout.java:749)         at com.flyco.tablayout.SlidingTabLayout.showDot(SlidingTabLayout.java:771)

### ISSUE THREAD

**Issue by kyriej** [H07000223/FlycoTabLayout#404]

**Comment by jimmonster** [comment]
我也是出现了这个问题

**Comment by jimmonster** [comment]
> _No description provided._

请问一下您是怎么解决的

**Comment by ali-bagheri** [comment]
I have too issue

**Comment by kyriej** [comment]
额，这个问题解决了，就是viewpagwe要设置好adapter然后再跟tab进行关联，具体看demo
