### ISSUE TITLE
用SlidingTabLayout+ViewPager，报java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.removeOnPageChangeListener

### ISSUE THREAD

**Issue by songj056** [H07000223/FlycoTabLayout#52]
1.使用场景：用SlidingTabLayout(CommonTabLayout不知道怎么不加载图片)切换ViewPager。
布局如下：
        <com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/tlChange"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="@dimen/size_unit_3"
            android:layout_marginRight="@dimen/size_unit_10"
            tl:tl_indicator_height="@dimen/line_size_unit"
            tl:tl_indicator_width="@dimen/size_unit_3" />

相关的代码：
        mPages = new ArrayList<View>();
        mInflater = getLayoutInflater();

        mProduct = mInflater.inflate(R.layout.view_product_detail_product, vpContent, false);// 商品
        mDetails = mInflater.inflate(R.layout.view_product_detail_details, vpContent, false);// 详情
        mComments = mInflater.inflate(R.layout.view_product_detail_comments, vpContent, false);// 评价

        // 将页面添加进去页面承载容器
        mPages.add(mProduct);
        mPages.add(mDetails);
        mPages.add(mComments);

        PagerAdapter adapter = new PagerAdapter() {
            @Override
            public int getCount() {
                return mPages.size();
            }

            @Override
            public boolean isViewFromObject(View view, Object object) {
                return view == object;
            }

            @Override
            public void destroyItem(ViewGroup container, int position, Object object) {
                container.removeView(mPages.get(position));
            }

            @Override
            public Object instantiateItem(ViewGroup container, int position) {
                View view = mPages.get(position);
                container.addView(view);
                return view;
            }
        };
        vpContent.setAdapter(adapter);

        **tlChange.setViewPager(vpContent, mTitles);**//~~~~~~ @H07000223 这行直接报错~~~~~~~
        tlChange.setCurrentTab(0);// 默认选中项

        vpContent.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                tlChange.setCurrentTab(position % (mPages.size()));
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });

        // 点击按钮切换页面
        tlChange.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelect(int position) {
                vpContent.setCurrentItem(position);
            }

            @Override
            public void onTabReselect(int position) {

            }
        });

~~~~~~~~~~~~~~~~~~~这样写有什么问题吗？

2.~~~~~~~报错如下：
java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.removeOnPageChangeListener
                                                                             at com.flyco.tablayout.SlidingTabLayout.setViewPager(SlidingTabLayout.java:202)
                                                                             at **com.test.ProductDetailActivity.init(ProductDetailActivity.java:228)
                                                                             at** com.test.ProductDetailActivity.onCreate(ProductDetailActivity.java:114)
                                                                             at android.app.Activity.performCreate(Activity.java:5255)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:154)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5308)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                             at dalvik.system.NativeStart.main(Native Method)

3.然后我在setViewPager(ViewPager vp, String[] titles)方法里面找到这两句：
        **this.mViewPager.removeOnPageChangeListener(this);// 这里报错？？**
        this.mViewPager.addOnPageChangeListener(this);

最后~~~~~~~~~~求原因和解决方案~~

**Comment by H07000223** [comment]
你的v4包版本太老了,不支持removeOnPageChangeListener和addOnPageChangeListener方法,升级一下应该就没问题

**Comment by songj056** [comment]
@H07000223 我用的support-v4:22.1.1，这个不算老吧？
