### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by 275873859** [H07000223/FlycoTabLayout#7]
将首页替换成getString(R.string.home)    崩溃

**Comment by H07000223** [comment]
应该不存在国际化的问题~具体些~贴下代码以及异常

**Comment by 275873859** [comment]
在demo中，直接将首页提取到 string中就崩溃了

**Comment by 275873859** [comment]
FATAL EXCEPTION: main
                                                                            Process: com.flyco.tablayoutsamples, PID: 15274
                                                                            java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.flyco.tablayoutsamples/com.flyco.tablayoutsamples.ui.CommonTabActivity}: java.lang.NullPointerException
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2126)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: java.lang.NullPointerException
                                                                                at android.content.ContextWrapper.getResources(ContextWrapper.java:89)
                                                                                at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:78)
                                                                                at android.content.Context.getString(Context.java:345)
                                                                                at com.flyco.tablayoutsamples.ui.CommonTabActivity.<init>(CommonTabActivity.java:30)
                                                                                at java.lang.Class.newInstanceImpl(Native Method)
                                                                                at java.lang.Class.newInstance(Class.java:1208)
                                                                                at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2117)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by H07000223** [comment]
这个跟TabLayout库无关.
不要在全局变量初始化中,使用getResource方法

```java
  private String[] mTitles;
  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_common_tab);

        mTitles = new String[]{getResources().getString(R.string.xxx), ...};
}
```

**Comment by 275873859** [comment]
谢谢

**Comment by tuzhao** [comment]
为什么不能在oncreate中使用getResource()？

2016-01-06 17:50 GMT+08:00 Flyco <notifications@github.com>:

**Comment by H07000223** [comment]
能在oncreate中使用getResource(),不要在全局变量定义的地方使用.
此时Activity还没创建,context拿不到为null
